### ISSUE TITLE
Unable to activate cocoapods-links-0.3.0, because json-2.0.2 conflicts with json (~> 1.8)

### ISSUE THREAD

**Issue by emarashliev** [mowens/cocoapods-links#6]
» pod list links                                                                                                                           
Error loading the plugin `cocoapods-links-0.3.0`.

Gem::ConflictError - Unable to activate cocoapods-links-0.3.0, because json-2.0.2 conflicts with json (~> 1.8)
/usr/local/opt/rbenv/versions/2.4.1/lib/ruby/2.4.0/rubygems/specification.rb:2291:in `raise_if_conflicts'
/usr/local/opt/rbenv/versions/2.4.1/lib/ruby/2.4.0/rubygems/specification.rb:1411:in `activate'
/usr/local/opt/rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/claide-1.0.2/lib/claide/command/plugin_manager.rb:93:in `safe_activate_and_require'
/usr/local/opt/rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/claide-1.0.2/lib/claide/command/plugin_manager.rb:31:in `block in load_plugins'
/usr/local/opt/rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/claide-1.0.2/lib/claide/command/plugin_manager.rb:30:in `map'
/usr/local/opt/rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/claide-1.0.2/lib/claide/command/plugin_manager.rb:30:in `load_plugins'
/usr/local/opt/rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/claide-1.0.2/lib/claide/command.rb:326:in `block in run'
/usr/local/opt/rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/claide-1.0.2/lib/claide/command.rb:325:in `each'
/usr/local/opt/rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/claide-1.0.2/lib/claide/command.rb:325:in `run'
/usr/local/opt/rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/cocoapods-1.2.1/lib/cocoapods/command.rb:52:in `run'
/usr/local/opt/rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/cocoapods-1.2.1/bin/pod:55:in `<top (required)>'
/usr/local/opt/rbenv/versions/2.4.1/bin/pod:22:in `load'
/usr/local/opt/rbenv/versions/2.4.1/bin/pod:22:in `<main>'

[!] Unknown command: `links`

**Comment by hfossli** [comment]
If you use Gemfile e.g. 

```
source "https://rubygems.org"

gem "fastlane"
gem "cocoapods"
gem "cocoapods-links"
```

then you may try to run `$ bundle update` and then you'll be able to resolve those conflicts most likely. 

Then you can run `bundle exec pod link` etc
