### ISSUE TITLE
unable to link to a pod

### ISSUE THREAD

**Issue by kambala-decapitator** [mowens/cocoapods-links#7]
### Command

```
bundle exec pod link mypod
```

### Report

* What did you do?

tried to link to a pod

* What did you expect to happen?

link succeeds

* What happened instead?

error:

```
NoMethodError - undefined method `include?' for #<CLAide::ARGV:0x00007fc96d9e40d8>
/Users/kambala/.bundler_gems/ruby/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/command.rb:101:in `ensure_not_root_or_allowed!'
/Users/kambala/.bundler_gems/ruby/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/command.rb:48:in `run'
/Users/kambala/.bundler_gems/ruby/2.6.0/gems/cocoapods-links-0.3.0/lib/pod/links.rb:72:in `link'
/Users/kambala/.bundler_gems/ruby/2.6.0/gems/cocoapods-links-0.3.0/lib/pod/command/link.rb:37:in `run'
/Users/kambala/.bundler_gems/ruby/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
/Users/kambala/.bundler_gems/ruby/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/command.rb:52:in `run'
/Users/kambala/.bundler_gems/ruby/2.6.0/gems/cocoapods-1.10.1/bin/pod:55:in `<top (required)>'
/Users/kambala/.bundler_gems/ruby/2.6.0/bin/pod:23:in `load'
/Users/kambala/.bundler_gems/ruby/2.6.0/bin/pod:23:in `<top (required)>'
/Library/Ruby/Gems/2.6.0/gems/bundler-2.2.20/lib/bundler/cli/exec.rb:63:in `load'
/Library/Ruby/Gems/2.6.0/gems/bundler-2.2.20/lib/bundler/cli/exec.rb:63:in `kernel_load'
/Library/Ruby/Gems/2.6.0/gems/bundler-2.2.20/lib/bundler/cli/exec.rb:28:in `run'
/Library/Ruby/Gems/2.6.0/gems/bundler-2.2.20/lib/bundler/cli.rb:474:in `exec'
/Library/Ruby/Gems/2.6.0/gems/bundler-2.2.20/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/Library/Ruby/Gems/2.6.0/gems/bundler-2.2.20/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
/Library/Ruby/Gems/2.6.0/gems/bundler-2.2.20/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
/Library/Ruby/Gems/2.6.0/gems/bundler-2.2.20/lib/bundler/cli.rb:30:in `dispatch'
/Library/Ruby/Gems/2.6.0/gems/bundler-2.2.20/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
/Library/Ruby/Gems/2.6.0/gems/bundler-2.2.20/lib/bundler/cli.rb:24:in `start'
/Library/Ruby/Gems/2.6.0/gems/bundler-2.2.20/exe/bundle:49:in `block in <top (required)>'
/Library/Ruby/Gems/2.6.0/gems/bundler-2.2.20/lib/bundler/friendly_errors.rb:128:in `with_friendly_errors'
/Library/Ruby/Gems/2.6.0/gems/bundler-2.2.20/exe/bundle:37:in `<top (required)>'
/usr/local/bin/bundle:23:in `load'
/usr/local/bin/bundle:23:in `<main>'
```

### Stack

```
   CocoaPods : 1.10.1
        Ruby : ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin20]
    RubyGems : 3.0.3
        Host : macOS 11.4 (20F71)
       Xcode : 12.5.1 (12E507)
         Git : git version 2.30.1 (Apple Git-130)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib
Repositories : trunk - CDN - https://cdn.cocoapods.org/
```

### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-links       : 0.3.0
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-trunk       : 1.5.0
cocoapods-try         : 1.2.0
```

**Comment by haifengkao** [comment]
@kambala-decapitator I have solved this issue and published a new gem. Please check it out
https://github.com/haifengkao/cocoapods-links-v2

**Comment by kambala-decapitator** [comment]
@haifengkao thanks, the error is solved!

but I encountered another issue with your pod :( Can't open an issue in your fork, will post here:

`pod repo push` and `pod lib lint` now fail:

```
Validating specs
 -> MyPod (0.2.0)
    - ERROR | [iOS] unknown: Encountered an unknown error (undefined method `help!' for Pod::Command::Links:Module) during validation.
```
